config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :reviews, except: [:index]
  resources :beers
  root 'home#home'
  get 'contact', to: 'home#contact'
  post 'request_contact', to: 'home#request_contact'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
    #a beer has many reviews which depend on it
    has_many :reviews, dependent: :destroy
    #validates if title, description and picture are not null
    validates :title, :description, :picture, presence: true
    #validates that the title is unique
    validates :title, uniqueness: true
end

app/models/review.rb
class Review < ActiveRecord::Base
  #user belongs to a beer and a user
  belongs_to :beer
  belongs_to :user
  #validates that rating and beer are not empty
  validates :rating, :beer, presence: true
  #validates that rating is only from 1 to 5
  validates :rating, :inclusion => {:in =>[1,2,3,4,5]}
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  
  #user can have many reviews and they will depend on the user       
  has_many :reviews, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]

  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.all
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
  end

  # GET /beers/new
  def new
    @beer = Beer.new
  end

  # GET /beers/1/edit
  def edit
  end

  # POST /beers
  # POST /beers.json
  def create
    @beer = Beer.new(beer_params)

    respond_to do |format|
      if @beer.save
        format.html { redirect_to @beer, notice: t('.create_success') }
        format.json { render :show, status: :created, location: @beer }
      else
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: t('.update_success') }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: t('.destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_beer
      @beer = Beer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def beer_params
      params.require(:beer).permit(:title, :description, :picture)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def home
  end
  
  def contact
  end
  
  #method for sending an email
  def request_contact
    name = params[:name]
    email = params[:email]
    message = params[:message]
    
    #displays an alert if there's no email
    if email.blank?
      flash[:alert] = I18n.t('home.request_contact.no_email')
    #sends email and gives success notice
    else
      ContactMailer.contact_email(email, name, message).deliver_now
      flash[:notice] = I18n.t('home.request_contact.email_sent')
    end
    
    redirect_to root_path
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :set_beer, only: [:new, :create]
  before_action :authenticate_user!

  # GET /reviews/new
  def new
    @review = @beer.reviews.new
  end

  # GET /reviews/1/edit
  def edit
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = @beer.reviews.new(review_params)
    @review.user = current_user

    respond_to do |format|
      if @review.save
        format.html { redirect_to root_path, notice: t('.create_success') }
        format.json { render :show, status: :created, location: @review }
      else
        format.html { render :new }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1
  # PATCH/PUT /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to @review, notice: t('.update_success') }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to root_path, notice: t('.destroy_success') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end
    
    #makes a beer for future use
    def set_beer
      @beer = Beer.find_by(id: params[:beer_id]) || Beer.find(review_params[:beer_id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def review_params
      params.require(:review).permit(:beer_id, :rating, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/beers/_form.html.haml
= form_for @beer do |f|
  - if @beer.errors.any?
    #error_explanation
      %h2= "#{pluralize(@beer.errors.count, "error")} prohibited this beer from being saved:"
      %ul
        - @beer.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :description
    = f.text_area :description
  .field
    = f.label :picture
    = f.text_field :picture
  .actions
    = f.submit 'Save'

app/views/beers/edit.html.haml
%h1 Editing beer

= render 'form'

= link_to 'Show', @beer
\|
= link_to 'Back', beers_path

app/views/beers/index.html.haml
%h1 Listing beers

%table.table.table-hover.table-condensed
  %thead
    %tr
      %th Title
      %th Description
      %th Picture
      %th
      %th
      %th

  %tbody
    - @beers.each do |beer|
      %tr
        %td= beer.title
        %td= beer.description
        %td= beer.picture
        %td= link_to 'Show', beer
        %td= link_to 'Edit', edit_beer_path(beer)
        %td= link_to 'Destroy', beer, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Beer', new_beer_path

app/views/beers/new.html.haml
%h1 New beer

= render 'form'

= link_to 'Back', beers_path

app/views/beers/show.html.haml
%p
  %b Title:
  = @beer.title
%p
  %b Description:
  = @beer.description
%p
  %b Picture:
  = @beer.picture
  
%h3 Reviews:

%table.table.table-hover.table-condensed
  %thead
    %tr
      %th Email
      %th Rating
      %th Comment
      %th
      %th
      
  %tbody
    - @beer.reviews.each do |review|
      %tr
        %td=review.user.email
        %td=review.rating
        %td=review.comment
        %td=link_to 'Edit', edit_review_path(review)
        %td=link_to 'Destroy', review, :method => :delete, :data => {:confirm => 'Are you sure?'}
  
%p= link_to t('.add'), new_review_path(beer_id: @beer)

= link_to 'Edit', edit_beer_path(@beer)
\|
= link_to 'Back', beers_path

app/views/home/contact.html.haml
%h1= t('.title')
%p= t('.contact_us')

= form_tag request_contact_path, method: 'post', id: 'form' do
    = label_tag :name, t('.name')
    = text_field_tag :name, '', title: t('.enter_name'), size: 50, :class => "required"
    
    = label_tag :email, t('.email')
    = email_field_tag :email, '', title: t('.enter_email'), :class => "required"
    
    = label_tag :message, t('.message')
    = text_field_tag :message, '', title: t('.enter_message'), size: 100, :class => "required"
    
    = submit_tag t('.submit')
    
%script
    $("#form").validate();

app/views/home/home.html.haml
%p=t('.welcome')

app/views/layouts/application.html.haml
!!!

%html
  %head
    %meta{'charset' => 'utf-8'}
    %meta{'http-equiv' => 'x-ua-compatible', 'content' => 'ie=edge'}

    %title= t('app_title')

    %meta{'name' => 'description', 'content' => t('app_description')}
    %meta{'name' => 'viewport', 'content' => 'width=device-width, initial-scale=1'}

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = javascript_include_tag 'modernizr'
    = csrf_meta_tags

  %body
  
    = render 'shared/header'

    = yield
    
    = render 'shared/footer'

app/views/reviews/_form.html.haml
= form_for @review do |f|
  - if @review.errors.any?
    #error_explanation
      %h2= "#{pluralize(@review.errors.count, "error")} prohibited this review from being saved:"
      %ul
        - @review.errors.full_messages.each do |msg|
          %li= msg

  .field
    = f.label :beer
    %p= @review.beer.title
    = f.hidden_field :beer_id, value: @review.beer.id
  .field
    = f.label :rating
    = f.number_field :rating
  .field
    = f.label :comment
    = f.text_area :comment
  .actions
    = f.submit 'Save'

app/views/reviews/edit.html.haml
%h1 Editing review

= render 'form'

= link_to 'Back', root_path

app/views/reviews/new.html.haml
%h1 New review

= render 'form'

= link_to 'Back', root_path

app/views/shared/_footer.html.haml
%footer.panel-footer.navbar-fixed-bottom
    %p=t('.copyright')

app/views/shared/_header.html.haml
%nav.navbar.navbar-default
    .container-fluid
        .navbar-header
            %ul.nav.navbar-nav
                %li
                    %a.navbar-brand{:href => "/"} 
                        = t(".title")
                
                %li
                    - if user_signed_in?
                        %li
                            = "#{current_user.email}"
                        %li
                            = link_to t('profile'), edit_user_registration_path
                        %li
                            = link_to t('logout'), destroy_user_session_path, method: 'delete'
                    - else
                        %li
                            = link_to t('login'), new_user_session_path
                        %li
                            = link_to t('sign_up'), new_user_registration_path
                %li
                    =link_to 'Beers', beers_path
                %li
                    =link_to 'Contact us', contact_path

- flash.each do |key, value|
    = content_tag :div, content_tag(:p, value), id: "#{key}" unless value.blank?